# jwt configuration
jwt:
  signing-key: 'C6C156395A0F3020CB5DD6B8A1D7C185'
  expires-time: 604800 #7天
  buffer-time: 86400 #1天
  issuer: 'ZGA sunJ'

# zap logger configuration
zap:
  # 可使用 "debug", "info", "warn", "error", "dpanic", "panic", "fatal",
  level: 'error'
  format: 'console'
  prefix: '[zga-client-manage]'
  director: 'log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# redis configuration
redis:
  addr: '127.0.0.1:6379'
  password: 'Alldo527'
  db: 0

# email configuration
email:
  host: 'smtp.office365.com'
  port: 587
  is-ssl: true
  from: 'gia-support@zenlayer.com'
  secret: 'Waz26044'
  to: 'xxx@qq.com'
  nickname: 'test'

# casbin configuration
casbin:
  model-path: './resource/rbac_model.conf'

# system configuration
system:
  env: 'public'  # Change to "develop" to skip authentication for development mode
  addr: 9000
  db-type: 'mysql'
  use-multipoint: false
  # IP限制次数 一个小时15000次
  iplimit-count: 15000
  #  IP限制一个小时
  iplimit-time: 3600

# captcha configuration
captcha:
  key-long: 6
  img-width: 240
  img-height: 80

# mysql connect configuration
mysql:
  path: '127.0.0.1'
  port: '3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'gva'
  username: 'root'
  password: 'root'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: "Info"
  log-zap: true

# timer task db clear table
Timer:
  start: true
  spec: "@daily"
  detail: [
    # tableName: 需要清理的表名
    # compareField: 需要比较时间的字段
    # interval: 时间间隔, 具体配置详看 time.ParseDuration() 中字符串表示 且不能为负数
    # 2160h = 24 * 30 * 3 -> 三个月
    { tableName: "sys_operation_records" , compareField: "created_at", interval: "2160h" },
    { tableName: "jwt_blacklists" , compareField: "created_at", interval: "168h" }
    #{ tableName: "log2" , compareField: "created_at", interval: "2160h" }
  ]

# 跨域配置
# 需要配合 server/initialize/router.go 使用
cors:
  mode: whitelist # 放行模式: allow-all, 放行全部; whitelist, 白名单模式, 来自白名单内域名的请求添加 cors 头; strict-whitelist 严格白名单模式, 白名单外的请求一律拒绝
  whitelist:
    - allow-origin: www.zenlayer.com
      allow-headers: content-type
      allow-methods: GET, POST
      expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
      allow-credentials: true # 布尔值
    - allow-origin: www.zenlayer.com
      allow-headers: content-type
      allow-methods: GET, POST
      expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
      allow-credentials: true # 布尔值
